num1=int(input("enter the number 1: "))
num2=int(input("enter the number 2: "))
num3=int(input("enter the number 3: "))
num4=int(input("enter the number 4: "))
greatest=max(num1,num2,num3,num4)
print("the Greatest number is ", greatest)